## Web Scraping with Julia

### Avik Sengupta, Julia Computing

#### JuliaCon 2017, Berkeley CA

In [14]:
Pkg.add("Cascadia")

INFO: Nothing to be done
INFO: METADATA is out-of-date — you may not have the latest version of Cascadia
INFO: Use `Pkg.update()` to get the latest versions of your packages


In [15]:
Pkg.add("HTTP")

INFO: Nothing to be done
INFO: METADATA is out-of-date — you may not have the latest version of HTTP
INFO: Use `Pkg.update()` to get the latest versions of your packages


In [3]:
using Cascadia
using HTTP
using Gumbo

In [3]:
r=HTTP.get("https://stackoverflow.com/questions/tagged/julia-lang?sort=newest&pagesize=50")

HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Cache-Control: private
Content-Type: text/html; charset=utf-8
X-Frame-Options: SAMEORIGIN
Set-Cookie: usr=p=[2|2][10|50]; expires=Wed, 06-Feb-2019 15:12:08 GMT; path=/; HttpOnly
X-Request-Guid: da400850-02a5-4ba1-ad3a-65749e973195
Strict-Transport-Security: max-age=15552000
Content-Security-Policy: upgrade-insecure-requests
Accept-Ranges: bytes
Age: 0
Content-Length: 210588
Accept-Ranges: bytes
Date: Mon, 06 Aug 2018 15:12:08 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-lcy19250-LCY
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1533568328.583483,VS0,VE512
Vary: Fastly-SSL
X-DNS-Prefetch-Control: off
Set-Cookie: prov=cbe38d1f-f60f-e4ff-a74d-9645b75e0729; domain=.stackoverflow.com; expires=Fri, 01-Jan-2055 00:00:00 GMT; path=/; HttpOnly

<!DOCTYPE html>


    <html itemscope itemtype="http://schema.org/QAPage" class="html__responsive">

    <head>

        <title>Newest &#39;julia-lang&#39; Questions - Stack Overflow</title>


In [4]:
typeof(r)

HTTP.Messages.Response

In [12]:
strResponse = String(r.body)

"<!DOCTYPE html>\r\n\r\n\r\n    <html itemscope itemtype=\"http://schema.org/QAPage\" class=\"html__responsive\">\r\n\r\n    <head>\r\n\r\n        <title>Newest &#39;julia-lang&#39; Questions - Stack Overflow</title>\r\n        <link rel=\"shortcut icon\" href=\"https://cdn.sstatic.net/Sites/stackoverflow/img/favicon.ico?v=4f32ecc8f43d\">\r\n        <link rel=\"apple-touch-icon image_src\" href=\"https://cdn.sstatic.net/Sites/stackoverflow/img/apple-touch-icon.png?v=c78bd457575a\">\r\n        <link rel=\"search\" type=\"application/opensearchdescription+xml\" title=\"Stack Overflow\" href=\"/opensearch.xml\">\r\n        <meta name=\"viewport\" content=\"width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0\">\r\n\r\n\r\n        <meta property=\"og:type\" content= \"website\" />\r\n        <meta property=\"og:url\" content=\"https://stackoverflow.com/questions/tagged/julia-lang?sort=newest&amp;pagesize=50\"/>\r\n        <meta property=\"og:site_name\" content=\"

In [13]:
h = parsehtml(strResponse)

HTML Document:
<!DOCTYPE html>
<HTML class="html__responsive"itemscope=""itemtype="http://schema.org/QAPage">
  <head>
    <title>
      Newest 'julia-lang' Questions - Stack Overflow
    </title>
    <link rel="shortcut icon"href="https://cdn.sstatic.net/Sites/stackoverflow/img/favicon.ico?v=4f32ecc8f43d"></link>
    <link rel="apple-touch-icon image_src"href="https://cdn.sstatic.net/Sites/stackoverflow/img/apple-touch-icon.png?v=c78bd457575a"></link>
    <link rel="search"href="/opensearch.xml"title="Stack Overflow"type="application/opensearchdescription+xml"></link>
    <meta name="viewport"content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0"></meta>
    <meta property="og:type"content="website"></meta>
    <meta property="og:url"content="https://stackoverflow.com/questions/tagged/julia-lang?sort=newest&pagesize=50"></meta>
    <meta property="og:site_name"content="Stack Overflow"></meta>
    <meta property="og:image"content="https://cdn.sstatic.n

In [14]:
typeof(h)

Gumbo.HTMLDocument

In [15]:
h.root.children[1].children[1]

Gumbo.HTMLElement{:title}:
<title>
  Newest 'julia-lang' Questions - Stack Overflow
</title>


In [16]:
s=Selector(".question-summary")

Cascadia.Selector(Cascadia.#7)

In [17]:
qs = matchall(s, h.root)

50-element Array{Gumbo.HTMLNode,1}:
 Gumbo.HTMLElement{:div}:
<div class="question-summary"id="question-summary-51706041">
  <div class="statscontainer">
    <div class="stats">
      <div class="vote">
        <div class="votes">
          <span class="vote-count-post ">
            <strong>
              0
            </strong>
          </span>
          <div class="viewcount">
            votes
          </div>
        </div>
      </div>
      <div class="status answered-accepted">
        <strong>
          1
        </strong>
        answer
      </div>
    </div>
    <div class="views "title="14 views">
      14 views
    </div>
  </div>
  <div class="summary">
    <h3>
      <a class="question-hyperlink"href="/questions/51706041/overloading-function-names-already-in-use-by-imported-modules">
        Overloading function names already in use by imported modules
      </a>
    </h3>
    <div class="excerpt">
      I want to define a function
      
      function f(a :: my_type,

In [18]:
author_elem = matchall(sel".user-details a",qs[1])

1-element Array{Gumbo.HTMLNode,1}:
 Gumbo.HTMLElement{:a}:
<a href="/users/9310251/hjab">
  hjab
</a>


In [19]:
author_elem[1].children[1]

HTML Text: hjab

In [20]:
text(author_elem[1].children[1])

"hjab"

In [21]:
s=sel"[rel=\"next\"]"

Cascadia.Selector(Cascadia.#7)

In [22]:
matchall(s, h.root)

1-element Array{Gumbo.HTMLNode,1}:
 Gumbo.HTMLElement{:a}:
<a href="/questions/tagged/julia-lang?page=2&sort=newest&pagesize=50"rel="next"title="go to page 2">
  <span class="page-numbers next">
    next
  </span>
</a>


In [23]:
matchall(s, h.root)[1]

Gumbo.HTMLElement{:a}:
<a href="/questions/tagged/julia-lang?page=2&sort=newest&pagesize=50"rel="next"title="go to page 2">
  <span class="page-numbers next">
    next
  </span>
</a>


In [24]:
nxt = getattr(matchall(s, h.root)[1], "href")

"/questions/tagged/julia-lang?page=2&sort=newest&pagesize=50"

In [4]:
const baseURL = "https://stackoverflow.com"

"https://stackoverflow.com"

In [26]:
HTTP.get("$baseURL$nxt")

HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Cache-Control: private
Content-Type: text/html; charset=utf-8
X-Frame-Options: SAMEORIGIN
Set-Cookie: usr=p=[2|2][10|50]; expires=Wed, 06-Feb-2019 19:57:05 GMT; path=/; HttpOnly
X-Request-Guid: 4055f573-1908-4d82-b3e8-b6fb5eabde3f
Strict-Transport-Security: max-age=15552000
Content-Security-Policy: upgrade-insecure-requests
Accept-Ranges: bytes
Age: 0
Content-Length: 209630
Accept-Ranges: bytes
Date: Mon, 06 Aug 2018 19:57:05 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-lcy19226-LCY
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1533585425.328796,VS0,VE93
Vary: Fastly-SSL
X-DNS-Prefetch-Control: off
Set-Cookie: prov=45ee0ff0-35af-0569-e4f7-651e3ae967cc; domain=.stackoverflow.com; expires=Fri, 01-Jan-2055 00:00:00 GMT; path=/; HttpOnly

<!DOCTYPE html>


    <html itemscope itemtype="http://schema.org/QAPage" class="html__responsive">

    <head>

        <title>Newest &#39;julia-lang&#39; Questions - Page 2 - Stack Overflow<

In [29]:
matchall(sel".question-summary", h.root)

50-element Array{Gumbo.HTMLNode,1}:
 Gumbo.HTMLElement{:div}:
<div class="question-summary"id="question-summary-51706041">
  <div class="statscontainer">
    <div class="stats">
      <div class="vote">
        <div class="votes">
          <span class="vote-count-post ">
            <strong>
              0
            </strong>
          </span>
          <div class="viewcount">
            votes
          </div>
        </div>
      </div>
      <div class="status answered-accepted">
        <strong>
          1
        </strong>
        answer
      </div>
    </div>
    <div class="views "title="14 views">
      14 views
    </div>
  </div>
  <div class="summary">
    <h3>
      <a class="question-hyperlink"href="/questions/51706041/overloading-function-names-already-in-use-by-imported-modules">
        Overloading function names already in use by imported modules
      </a>
    </h3>
    <div class="excerpt">
      I want to define a function
      
      function f(a :: my_type,

In [33]:
function count_julia_q()
    h = parsehtml(String(HTTP.get("$baseURL/questions/tagged/julia-lang?sort=newest&pagesize=50").body));
    s1=sel".question-summary"
    s2=sel"[rel=\"next\"]"
    count = 0
    while true
        q = matchall(s1, h.root)
        count = count + length(q)
        elem = matchall(s2, h.root)
        if length(elem) > 0
            nxt = getattr(elem[1], "href")
            h = parsehtml(String(HTTP.get("$baseURL$nxt").body))
        else
            break
        end
    end
    println("Total number of Julia Questions: $count")
end

@time count_julia_q()

Total number of Julia Questions: 4264
 46.109274 seconds (19.57 M allocations: 1.315 GiB, 1.68% gc time)


In [5]:
const queue = Channel(10)
const count2 = Ref{Int}()

put!(queue, "$baseURL/questions/tagged/julia-lang?sort=newest&pagesize=50")

function count_julia_q_async()
    s1=sel".question-summary"
    s2=sel"[rel=\"next\"]"
    @sync while true
        u = take!(queue)
        if u == nothing; break; end
        @async begin 
            h = parsehtml(String(HTTP.get(u).body));
            q = matchall(s1, h.root)
            count2[] = count2[] + length(q)
            elem = matchall(s2, h.root)
            if length(elem) > 0
                nx = getattr(elem[1], "href")
                put!(queue, "$baseURL$nx")
            else
                put!(queue, nothing)
            end
        end
    end

end

@time count_julia_q_async()

 52.963037 seconds (21.65 M allocations: 1.402 GiB, 0.73% gc time)


In [8]:
function count_q(tag)
           client = HTTP.Client()
           h1 = parsehtml(String(HTTP.get(client, "$baseURL/questions/tagged/$tag?sort=newest&pagesize=50").body));
           s1=sel".question-summary"
           s2=sel"[rel=\"next\"]"
           count = 0
           client = HTTP.Client()
           while true
               q = matchall(s1, h1.root)
               count = count + length(q)
               elem = matchall(s2, h1.root)
               if length(elem) > 0
                   nx = getattr(elem[1], "href")
                   h1 = parsehtml(String(HTTP.get(client, "$baseURL$nx").body))
               else
                   break
               end
           end
           println("Total number of $tag Questions: $count")
end


count_q (generic function with 1 method)

In [9]:
@time @sync for i in ["julia-lang", "sencha-touch", "jni"]
    @async count_q(i)
end

Total number of julia-lang Questions: 4264
Total number of sencha-touch Questions: 4725
Total number of jni Questions: 8066
1306.365822 seconds (81.46 M allocations: 5.347 GiB, 0.20% gc time)


In [39]:
h = parsehtml(String(take!(HTTP.get("$baseURL/questions/tagged/sencha-touch?sort=newest&pagesize=50"))))

LoadError: TimeoutException: server did not respond for more than 15.0 seconds. 

In [ ]:
matchall(sel".question-summary", h.root)

In [37]:
2+2

4

In [41]:
function count_qs(tag)
           client = HTTP.Client()
           h1 = parsehtml(String(take!(HTTP.get(client, "$baseURL/questions/tagged/$tag?sort=newest&pagesize=50"))));
           s1=sel".question-summary"
           s2=sel"[rel=\"next\"]"
           count = 0
           client = HTTP.Client()
           while true
            sleep(1)
               q = matchall(s1, h1.root)
               count = count + length(q)
               elem = matchall(s2, h1.root)
               if length(elem) > 0
                   nx = getattr(elem[1], "href")
                   h1 = parsehtml(String(take!(HTTP.get(client, "$baseURL$nx"))))
               else
                   break
               end
           end
           println("Total number of $tag Questions: $count")
end


count_qs (generic function with 1 method)

In [42]:
function count_qs_async(tags)
    @sync for i in tags
    @async count_qs(i)
    end
end

count_qs_async (generic function with 1 method)

In [44]:
alltags = ["julia-lang", "sencha-touch", "jni", "popen", "chromecast", "freebsd", "spree", "eigen", "thrift" ]

9-element Array{String,1}:
 "julia-lang"  
 "sencha-touch"
 "jni"         
 "popen"       
 "chromecast"  
 "freebsd"     
 "spree"       
 "eigen"       
 "thrift"      

In [45]:
alltags = reshape(alltags, 3, 3)

3×3 Array{String,2}:
 "julia-lang"    "popen"       "spree" 
 "sencha-touch"  "chromecast"  "eigen" 
 "jni"           "freebsd"     "thrift"

In [50]:
alltags = [alltags[:, i] for i in 1:size(alltags, 2)]

3-element Array{Array{String,1},1}:
 String["julia-lang","sencha-touch","jni"]
 String["popen","chromecast","freebsd"]   
 String["spree","eigen","thrift"]         

In [2]:
using JuliaRun
ctx = JuliaRun.init()
init_parallel()
nb=self()
scale!(ctx, nb, 3)

23-Jun 16:43:39:INFO:root:Compute cluster: 6896259441217669969 at https://kubernetes.default:443/
23-Jun 16:43:40:INFO:root:changing scale of nb-6896259441217669969 to 3
23-Jun 16:43:42:INFO:root:unsupported projectcalico.org/v1


In [5]:
nworkers()

1

In [4]:
scale(ctx,nb)

(3,3)

In [ ]:
@everywhere Pkg.add("Cascadia")
@everywhere Pkg.add("HTTP")
@everywhere using Cascadia
@everywhere using Gumbo
@everywhere using HTTP

In [ ]:
pmap(count_qs_async, alltags)